# Component DAG (MVP) — source-of-truth
#
# Цель:
# - Декларативно описать зависимости (DAG) между компонентами/модулями на уровне DataProcessor,
#   чтобы построить "priority" как dependency-ordering и определить параллелизм.
# - В MVP хранится в репозитории. Позже мигрируем в БД профилей анализа.
#
# Важно:
# - Это НЕ runtime state. Runtime состояние пишется в state-files (`run_state.json`, `state_*.json`).
# - Здесь мы фиксируем именно "что зависит от чего".
#
# Формат MVP (пока черновой, будет расширяться по мере аудита модулей):

version: 0.1

stages:
  baseline:
    nodes: []
  v1:
    nodes: []
  v2:
    nodes: []

# node schema:
# - component_name: string
# - owner_processor: one of [fetcher, segmenter, visual, audio, text, models, orchestrator]
# - depends_on_components: [string]   # hard deps: без них старт запрещён
# - soft_dependencies: [string]       # optional: влияет на качество, но не блокирует
# - wait_on_checkpoints: [string]     # сахар: например ["ocr_ready"]
#
# Пример (иллюстративный, НЕ утверждённый — заполним после аудита модулей):
# stages:
#   baseline:
#     nodes:
#       - component_name: segmenter
#         owner_processor: segmenter
#         depends_on_components: [fetcher]
#         soft_dependencies: []
#         wait_on_checkpoints: []
#       - component_name: core_clip
#         owner_processor: visual
#         depends_on_components: [segmenter]
#         soft_dependencies: []
#         wait_on_checkpoints: [frames_ready]

