# Component DAG (MVP) — source-of-truth
#
# Цель:
# - Декларативно описать зависимости (DAG) между компонентами/модулями на уровне DataProcessor,
#   чтобы построить "priority" как dependency-ordering и определить параллелизм.
# - В MVP хранится в репозитории. Позже мигрируем в БД профилей анализа.
#
# Важно:
# - Это НЕ runtime state. Runtime состояние пишется в state-files (`run_state.json`, `state_*.json`).
# - Здесь мы фиксируем именно "что зависит от чего".
#
# Формат MVP (пока черновой, будет расширяться по мере аудита модулей):

version: 0.1

stages:
  baseline:
    nodes:
      # --- Processor-level ---
      - component_name: segmenter
        owner_processor: segmenter
        depends_on_components: []
        soft_dependencies: []
        wait_on_checkpoints: []

      # --- Visual core providers (Tier-0) ---
      - component_name: core_clip
        owner_processor: visual
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: core_face_landmarks
        owner_processor: visual
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: core_object_detections
        owner_processor: visual
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: core_depth_midas
        owner_processor: visual
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: core_optical_flow
        owner_processor: visual
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      # --- Visual modules (Tier-0) ---
      - component_name: cut_detection
        owner_processor: visual
        depends_on_components: [segmenter, core_face_landmarks, core_object_detections]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: shot_quality
        owner_processor: visual
        depends_on_components:
          - segmenter
          - cut_detection
          - core_clip
          - core_depth_midas
          - core_object_detections
          - core_face_landmarks
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: scene_classification
        owner_processor: visual
        depends_on_components: [segmenter]
        soft_dependencies: [core_clip]
        wait_on_checkpoints: []

      - component_name: video_pacing
        owner_processor: visual
        depends_on_components: [segmenter, core_optical_flow, core_clip]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: uniqueness
        owner_processor: visual
        depends_on_components: [segmenter, core_clip]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: story_structure
        owner_processor: visual
        depends_on_components: [segmenter, core_clip, core_optical_flow, core_face_landmarks]
        soft_dependencies: []
        wait_on_checkpoints: []

      # --- Audio tier-0 (optional in baseline profile) ---
      - component_name: clap_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: loudness_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: tempo_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

  # --- Audio non-baseline / prod-important (audited, but not in baseline DAG) ---
  audio_extended:
    nodes:
      - component_name: asr_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: speaker_diarization_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: emotion_diarization_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: source_separation_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

      - component_name: speech_analysis_extractor
        owner_processor: audio
        depends_on_components: [segmenter]
        soft_dependencies: []
        wait_on_checkpoints: []

  v1:
    nodes: []
  v2:
    nodes: []

# node schema:
# - component_name: string
# - owner_processor: one of [fetcher, segmenter, visual, audio, text, models, orchestrator]
# - depends_on_components: [string]   # hard deps: без них старт запрещён
# - soft_dependencies: [string]       # optional: влияет на качество, но не блокирует
# - wait_on_checkpoints: [string]     # сахар: например ["ocr_ready"]
#
# Пример (иллюстративный, НЕ утверждённый — заполним после аудита модулей):
# stages:
#   baseline:
#     nodes:
#       - component_name: segmenter
#         owner_processor: segmenter
#         depends_on_components: [fetcher]
#         soft_dependencies: []
#         wait_on_checkpoints: []
#       - component_name: core_clip
#         owner_processor: visual
#         depends_on_components: [segmenter]
#         soft_dependencies: []
#         wait_on_checkpoints: [frames_ready]

